# Generated by Django 5.1.4 on 2025-01-16 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default='My expenses'),
            preserve_default=False,
        ),
    ]
