# Generated by Django 5.0.7 on 2025-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='Expenses', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
